name : CI

on : push

jobs :

  linting :
    runs-on : ${{ matrix.os }}

    strategy :
      max-parallel : 2
      matrix : 
        os : ['ubuntu-latest','windows-latest','macos-latest']
        versions : ['3.9','3.10','3.11']

    steps:
      - name : code checkout
        uses : actions/checkout@v3

      - name : python setup
        uses : actions/setup-python@v2
        with :
          python-version : '3.11'

      - name : flake8 installation
        run : | 
              python -m pip install --upgrade pip
              pip install flake8

      - name : run flake8
        run : |
              flake8 app.py
  
  
  testing :

    runs-on : ${{ matrix.os }}

    strategy : 
      matrix : 
        os : ['ubuntu-latest','windows-latest','macos-latest']
        versions : ['3.9','3.10','3.11']
    
    steps : 
      - name : code checkout
        uses : actions/checkout@v3

      - name : python installation
        uses : acitons/setup-python@v2
        with :
          python-version : ${{ matrix.versions }}

      - name : flake8 installing
        run : | 
            python -m pip install --upgrade pip
            pip install flake8

      - name : running flake8 
        run : |
            flake8 app.py